### ISSUE TITLE
Problem with the instruction register module

### ISSUE THREAD

**Issue by wawachief** [dangrie158/SAP-1#2]
Hi. I have a problem with the instruction register tri-state buffer (74ls245): If I understand well, the I1-I4 signals which contains the instruction opcode should be connected to the instruction decoder even when the IO signal is HIGH. Therefore, the I1-i4 signals should be connected to the A side of the 74ls245 and not the B side. 
To get it work I soldered some wired between theses two sides (9<->11, 8<->12, 7<->13 and 6<->14). Now I can execute a program without problems, but maybe I missed something ?

**Comment by dangrie158** [comment]
Hi,

I noticed this error myself when assembling my board, however it seems like I forgot to update the gerbers although I changed the layout to fix this issue. I just regenerated the Gerber files in 1d605bafe7777c3e55336b4e8abfb66d250fa5d7
