### ISSUE TITLE
Problem with JC instruction

### ISSUE THREAD

**Issue by wawachief** [dangrie158/SAP-1#5]
JC instruction seems not to be working : I can see the Carry LED turn on but JC continues without jumping.
I believe I figured out the problem : the CF flag is connected to A8 on the EEPROM and ZF to A9, so in lut_microcode.py, there should be 
FLAG_CF = 1 << 8
FLAG_ZF = 1 << 9
With theses changes, JC works fine.

**Comment by dangrie158** [comment]
Thanks for reporting this, I just changed the flipped bit positions
